### ISSUE TITLE
Loginfile updates fail

### ISSUE THREAD

**Issue by maelstromsh** [TheCheatsrichter/Gw2_Launchbuddy#237] opened 2021-05-25 21:25 UTC
Having an issue where launchbuddy will attempt to update a loginfile but will just get stuck on the gw2 launcher and never close it. It repeatedly brings the gw2 launcher above other windows but never does anything even after I manually click login. Manually closing it just results in launchbuddy saying "UPDATE REQUIRED" on all accounts. Cannot repair loginfiles since launchbuddy will not close the gw2 launcher after logging in and if closing them manually nothing happens.

**Comment by evertonrrodrigues** [comment] 2021-05-25 22:14
> Having an issue where launchbuddy will attempt to update a loginfile but will just get stuck on the gw2 launcher and never close it. It repeatedly brings the gw2 launcher above other windows but never does anything even after I manually click login. Manually closing it just results in launchbuddy saying "UPDATE REQUIRED" on all accounts. Cannot repair loginfiles since launchbuddy will not close the gw2 launcher after logging in and if closing them manually nothing happens.

I have the exactly same issue.

**Comment by bloggingninja** [comment] 2021-05-25 22:16
Same issue here, although I am going to mention that the auto-login doesn't seem to be working for me anymore either.

**Comment by anonymous3123** [comment] 2021-05-25 22:19
Same. I was able to trick it into signing into 4 accounts once, then it became too much trying to get my other accounts connected at the same time, so I'll wait for a fix.

**Comment by Apotekar** [comment] 2021-05-25 22:32
Same issue, new GW2 patch killed it for me even rapair login on all accounts and reinstall LB no change hope for a fast fix thx in advance.

**Comment by akeck** [comment] 2021-05-25 22:56
same issue here, too...

**Comment by WolfSabian** [comment] 2021-05-25 23:04
Same issue. Hoping for a fix or work around.

**Comment by WolfSabian** [comment] 2021-05-25 23:25
So, I've got it working, but I can't reliably explain how other than cancel the login repairs on start up and launch normally. Cancel it fast enough and it should load.
![Uploading 20210525_192529.jpg…]()

**Comment by AZDarkknight** [comment] 2021-05-25 23:34
I have had the same issue for the last couple of anet updates, having double figure accounts it becomes a bit of a pain having to go in and repair loginfile to each, especially after a new build where bug fixes follow a  couple of times during the day. Hoping for a fix too :)

**Comment by AZDarkknight** [comment] 2021-05-25 23:44
Same issue , although tbh Ive been having launcher update issues since this latest version was released but this is a step further as before I could repair each login individually.

**Comment by ryanlammers** [comment] 2021-05-25 23:44
I'm also having the same issue.

**Comment by FoolMeOnce** [comment] 2021-05-25 23:46
I'm also having the same issue.

**Comment by Jiansarys** [comment] 2021-05-26 00:20
Same was happening to me so I removed it, downloaded it again and now I can't even get it to come up. I get this instead 
![image](https://user-images.githubusercontent.com/69999016/119584498-a5d6e480-bd96-11eb-8af0-0a16f3dd8138.png)

**Comment by Jiansarys** [comment] 2021-05-26 00:36
I just got it working again by installing old version Gw2 Launchbuddy V2.2.0

**Comment by VathanaJr** [comment] 2021-05-26 01:00
I have the same issue, and I got it to work again using V2.3.1. However, the "UPDATE REQUIRED" info won't disappear, and LB still attempts to update the login files every time, but then just the launchers will reopen successfully.

**Comment by maelstromsh** [comment] 2021-05-26 02:30
> I just got it working again by installing old version Gw2 Launchbuddy V2.2.0

This seems to have solved the issue, at least temporarily

**Comment by nicodemus4802** [comment] 2021-05-26 04:30
I was able to fix this by replacing `<gw2build>115267</gw2build>` with `<gw2build>115781</gw2build>`in the `%APPDATA%\Gw2 Launchbuddy\Accs.xml` file. I no longer get the "UPDATE REQUIRED" notice, and the login file no longer tries to update as I open LB. This will have to be my temporary fix until updates are properly applied to the `%APPDATA%\Gw2 Launchbuddy\Accs.xml` file.

**Comment by Ashanielle** [comment] 2021-05-26 07:45
> I was able to fix this by replacing `<gw2build>115267</gw2build>` with `<gw2build>115781</gw2build>`in the `%APPDATA%\Gw2 Launchbuddy\Accs.xml` file. I no longer get the "UPDATE REQUIRED" notice, and the login file no longer tries to update as I open LB. This will have to be my temporary fix until updates are properly applied to the `%APPDATA%\Gw2 Launchbuddy\Accs.xml` file.

Can confirm that this does fix it for me as well. Thank you Nicodemus!

**Comment by Aldeguerra** [comment] 2021-05-26 11:00
> I was able to fix this by replacing `<gw2build>115267</gw2build>` with `<gw2build>115781</gw2build>`in the `%APPDATA%\Gw2 Launchbuddy\Accs.xml` file. I no longer get the "UPDATE REQUIRED" notice, and the login file no longer tries to update as I open LB. This will have to be my temporary fix until updates are properly applied to the `%APPDATA%\Gw2 Launchbuddy\Accs.xml` file.

This works, thank you so much Nicodemus4802 !!

**Comment by AdriCortesia** [comment] 2021-05-26 14:00
> 
> 
> I was able to fix this by replacing `<gw2build>115267</gw2build>` with `<gw2build>115781</gw2build>`in the `%APPDATA%\Gw2 Launchbuddy\Accs.xml` file. I no longer get the "UPDATE REQUIRED" notice, and the login file no longer tries to update as I open LB. This will have to be my temporary fix until updates are properly applied to the `%APPDATA%\Gw2 Launchbuddy\Accs.xml` file.

Do I have to save it in a "special way"? every time I change the parameter the old config overwrites it

**Comment by Ashanielle** [comment] 2021-05-26 14:20
> > I was able to fix this by replacing `<gw2build>115267</gw2build>` with `<gw2build>115781</gw2build>`in the `%APPDATA%\Gw2 Launchbuddy\Accs.xml` file. I no longer get the "UPDATE REQUIRED" notice, and the login file no longer tries to update as I open LB. This will have to be my temporary fix until updates are properly applied to the `%APPDATA%\Gw2 Launchbuddy\Accs.xml` file.
> 
> Do I have to save it in a "special way"? every time I change the parameter the old config overwrites it

That happened to me. I must have been tired because I had launchbuddy open so of course it wouldn't save. Not sure if that was your issue, but make sure you have launchbuddy closed, then do the changes, then save.

**Comment by AdriCortesia** [comment] 2021-05-26 14:28
> 
> 
> > > I was able to fix this by replacing `<gw2build>115267</gw2build>` with `<gw2build>115781</gw2build>`in the `%APPDATA%\Gw2 Launchbuddy\Accs.xml` file. I no longer get the "UPDATE REQUIRED" notice, and the login file no longer tries to update as I open LB. This will have to be my temporary fix until updates are properly applied to the `%APPDATA%\Gw2 Launchbuddy\Accs.xml` file.
> > 
> > 
> > Do I have to save it in a "special way"? every time I change the parameter the old config overwrites it
> 
> That happened to me. I must have been tired because I had launchbuddy open so of course it wouldn't save. Not sure if that was your issue, but make sure you have launchbuddy closed, then do the changes, then save.

I closed all GW2 related things. I changed the config. Interestingly only aroung 1/2 of my accounts work

**Comment by Ashanielle** [comment] 2021-05-26 14:38
> > > > I was able to fix this by replacing `<gw2build>115267</gw2build>` with `<gw2build>115781</gw2build>`in the `%APPDATA%\Gw2 Launchbuddy\Accs.xml` file. I no longer get the "UPDATE REQUIRED" notice, and the login file no longer tries to update as I open LB. This will have to be my temporary fix until updates are properly applied to the `%APPDATA%\Gw2 Launchbuddy\Accs.xml` file.
> > > 
> > > 
> > > Do I have to save it in a "special way"? every time I change the parameter the old config overwrites it
> > 
> > 
> > That happened to me. I must have been tired because I had launchbuddy open so of course it wouldn't save. Not sure if that was your issue, but make sure you have launchbuddy closed, then do the changes, then save.
> 
> I closed all GW2 related things. I changed the config. Interestingly only aroung 1/2 of my accounts work

I know before I applied this fix I had gone through and repaired all the log in files manually and I also have all the logins saved manually on launchbuddy as well. Not sure if that's the difference?

**Comment by Ashanielle** [comment] 2021-05-26 14:43
> > > > > > I was able to fix this by replacing `<gw2build>115267</gw2build>` with `<gw2build>115781</gw2build>`in the `%APPDATA%\Gw2 Launchbuddy\Accs.xml` file. I no longer get the "UPDATE REQUIRED" notice, and the login file no longer tries to update as I open LB. This will have to be my temporary fix until updates are properly applied to the `%APPDATA%\Gw2 Launchbuddy\Accs.xml` file.
> > > > > 
> > > > > 
> > > > > Do I have to save it in a "special way"? every time I change the parameter the old config overwrites it
> > > > 
> > > > 
> > > > That happened to me. I must have been tired because I had launchbuddy open so of course it wouldn't save. Not sure if that was your issue, but make sure you have launchbuddy closed, then do the changes, then save.
> > > 
> > > 
> > > I closed all GW2 related things. I changed the config. Interestingly only aroung 1/2 of my accounts work
> > 
> > 
> > I know before I applied this fix I had gone through and repaired all the log in files manually and I also have all the logins saved manually on launchbuddy as well. Not sure if that's the difference?
> 
> I've repaired my login files manually as well with the repair function under account settings. Then I tried the fix and only 3/7 accounts work and the others still "require an update"

Did you do cntrl+F using "gw2build" as the search term in your notepad doc of the config file to make sure you found all instances of that parameter?

**Comment by nicodemus4802** [comment] 2021-05-26 14:43
> > > > > > I was able to fix this by replacing `<gw2build>115267</gw2build>` with `<gw2build>115781</gw2build>`in the `%APPDATA%\Gw2 Launchbuddy\Accs.xml` file. I no longer get the "UPDATE REQUIRED" notice, and the login file no longer tries to update as I open LB. This will have to be my temporary fix until updates are properly applied to the `%APPDATA%\Gw2 Launchbuddy\Accs.xml` file.
> > > > > 
> > > > > 
> > > > > Do I have to save it in a "special way"? every time I change the parameter the old config overwrites it
> > > > 
> > > > 
> > > > That happened to me. I must have been tired because I had launchbuddy open so of course it wouldn't save. Not sure if that was your issue, but make sure you have launchbuddy closed, then do the changes, then save.
> > > 
> > > 
> > > I closed all GW2 related things. I changed the config. Interestingly only aroung 1/2 of my accounts work
> > 
> > 
> > I know before I applied this fix I had gone through and repaired all the log in files manually and I also have all the logins saved manually on launchbuddy as well. Not sure if that's the difference?
> 
> I've repaired my login files manually as well with the repair function under account settings. Then I tried the fix and only 3/7 accounts work and the others still "require an update"

It's possible that your other 4/7 accounts weren't updated to build 115267 prior to GW2's update yesterday. You'll want to make sure that all accounts have the 115781 build set in this file.

**Comment by nicodemus4802** [comment] 2021-05-26 14:49
> > > > > > > > I was able to fix this by replacing `<gw2build>115267</gw2build>` with `<gw2build>115781</gw2build>`in the `%APPDATA%\Gw2 Launchbuddy\Accs.xml` file. I no longer get the "UPDATE REQUIRED" notice, and the login file no longer tries to update as I open LB. This will have to be my temporary fix until updates are properly applied to the `%APPDATA%\Gw2 Launchbuddy\Accs.xml` file.
> > > > > > > 
> > > > > > > 
> > > > > > > Do I have to save it in a "special way"? every time I change the parameter the old config overwrites it
> > > > > > 
> > > > > > 
> > > > > > That happened to me. I must have been tired because I had launchbuddy open so of course it wouldn't save. Not sure if that was your issue, but make sure you have launchbuddy closed, then do the changes, then save.
> > > > > 
> > > > > 
> > > > > I closed all GW2 related things. I changed the config. Interestingly only aroung 1/2 of my accounts work
> > > > 
> > > > 
> > > > I know before I applied this fix I had gone through and repaired all the log in files manually and I also have all the logins saved manually on launchbuddy as well. Not sure if that's the difference?
> > > 
> > > 
> > > I've repaired my login files manually as well with the repair function under account settings. Then I tried the fix and only 3/7 accounts work and the others still "require an update"
> > 
> > 
> > It's possible that your other 4/7 accounts weren't updated to build 115267 prior to GW2's update yesterday. You'll want to make sure that all accounts have the 115781 build set in this file.
> 
> That's it! I thought it was just one entry! Thank you nicodemus you saved my day

I'm happy to have helped in some small way. TheCheatsrichter is the real hero to have brought this tool into the community though. In case you're ever wondering what build to update your tool to, you can take a look at the build number in the bottom-right corner of the official launcher.

![image](https://user-images.githubusercontent.com/37150186/119681387-a2c80c80-be07-11eb-8aef-4401c59b1fa9.png)

**Comment by Grimleiv** [comment] 2021-05-26 14:52
I did same as some over, went back to older version. The newest version cannon be uset atm it seems like. It do not update.. And keep asking for update what ever i do. Even tried to delete accounts, then with new installed client and lunchbuddy, still the latest version do not work. So not much to do.. until creator logs back in.

**Comment by MCA991** [comment] 2021-05-26 16:27
Same here. Had to use an older version (2.2.0).

**Comment by Flapjakk** [comment] 2021-05-26 21:56
> 
> 
> So, I've got it working, but I can't reliably explain how other than cancel the login repairs on start up and launch normally. Cancel it fast enough and it should load.
> ![20210525_192529](https://user-images.githubusercontent.com/49987935/119581129-f991ff80-bd8f-11eb-84bd-0d293c292b69.jpg)

Be careful with the earlier poster's suggestion to quickly cancel the login repairs. I tried this - not sure how what I clicked compared to him - and it broke the GW2 install. GW2 wont run, windows wont uninstall it, a repair installation does nothing, and a re-install produces the same error as when it first broke. 

At this moment, i still cant run GW2 after trying to cancel LaunchBuddy's login repairs.

![gw2 wont run](https://user-images.githubusercontent.com/84879230/119736305-8221a600-be4b-11eb-8e25-d869c4a170a4.png)

**Comment by WolfSabian** [comment] 2021-05-26 22:29
> Be careful with the earlier poster's suggestion to quickly cancel the login repairs. I tried this - not sure how what I clicked compared to him - and it broke the GW2 install. GW2 wont run, windows wont uninstall it, a repair installation does nothing, and a re-install produces the same error as when it first broke.
> 
> At this moment, i still cant run GW2 after trying to cancel LaunchBuddy's login repairs.

Weird. I did this numerous times without issue.  Hopefully you get it working again.

The suggestion to edit the Accs.xml is the way to go. Just make sure to edit each account within the file.

> I was able to fix this by replacing `<gw2build>115267</gw2build>` with `<gw2build>115781</gw2build>`in the `%APPDATA%\Gw2 Launchbuddy\Accs.xml` file. I no longer get the "UPDATE REQUIRED" notice, and the login file no longer tries to update as I open LB. This will have to be my temporary fix until updates are properly applied to the `%APPDATA%\Gw2 Launchbuddy\Accs.xml` file.

**Comment by SamMackrill** [comment] 2021-05-26 22:53
Note: Build number is now 115815

**Comment by Ezenami** [comment] 2021-05-26 23:13
Same all accounts require Update but update process just gets stuck

**Comment by Jiansarys** [comment] 2021-05-27 01:14
Well it was working all night after I switched to 2.2, but today it's messed up again.

**Comment by AdriCortesia** [comment] 2021-05-27 03:13
> 
> 
> Well it was working all night after I switched to 2.2, but today it's messed up again. Instead of the update thing from yesterday I now get this
> ![image](https://user-images.githubusercontent.com/69999016/119750506-7b089100-be67-11eb-9852-a1a07e3922a9.png)

Same for me. The build is new i tried it with that but doesn't work

**Comment by AZDarkknight** [comment] 2021-05-27 05:50
> 
> 
> > Well it was working all night after I switched to 2.2, but today it's messed up again. Instead of the update thing from yesterday I now get this
> > ![image](https://user-images.githubusercontent.com/69999016/119750506-7b089100-be67-11eb-9852-a1a07e3922a9.png)
> 
> Same for me. The build number is new so i tried it with that but doesn't work

I got this, so I closed it and opened my GW2 the ordinary way so the build would update. Then I opened buddy  and repaired login credentials for each account. Then it worked fine using 2.2 Hope that helps.

**Comment by Amancham** [comment] 2021-05-27 07:30
Had the same issue, was driving me nuts yesterday. Thanks to @nicodemus4802 for the suggested fix. It worked for me. I'm still using the newest version of LB.

**Comment by Jiansarys** [comment] 2021-05-27 09:22
Any word as to when this will be fixed?

**Comment by Jiansarys** [comment] 2021-05-27 09:25
> > I was able to fix this by replacing `<gw2build>115267</gw2build>` with `<gw2build>115781</gw2build>`in the `%APPDATA%\Gw2 Launchbuddy\Accs.xml` file. I no longer get the "UPDATE REQUIRED" notice, and the login file no longer tries to update as I open LB. This will have to be my temporary fix until updates are properly applied to the `%APPDATA%\Gw2 Launchbuddy\Accs.xml` file.
> 
> Can confirm that this does fix it for me as well. Thank you Nicodemus!

I have no gw2 after %appdata%

**Comment by Jiansarys** [comment] 2021-05-27 09:40
And now my whole game is messed up. Althought I have everything set correctly at 1440-, everything is huge like I'm playing with all bloom and processing, andf at around 720p. HUGE graphice, and I can'ty undo it now even by removing Launchbuddy.

**Comment by Jiansarys** [comment] 2021-05-27 09:49
Ty for resetting everything in the game. No clue how that was even possible by simpley launching your bunk every couple mins, but you manages to kill all my settings. I'm done with this shit

**Comment by nrone** [comment] 2021-05-27 09:52
@Jiansarys if you are not sure what you are doing, you should wait for a official fix.
"%APPDATA%\Gw2 Launchbuddy" is the folder you are looking for, not "%APPDATA%\Gw2"

**Comment by Jiansarys** [comment] 2021-05-27 09:59
@nrone I know what I'm doing. I was only relaunching and nothing more. I went to apdata and there was nothing there. I found it which btw it was in roaming, but I didn't mess with it. I launched it one more time in hope it would work, and all my game settings on all 4 acounts were gone.

**Comment by VathanaJr** [comment] 2021-05-27 10:29
@Jiansarys %APPDATA% is the C:\Users\You\AppData\Roaming folder. And if you didn't mess with it, it's not his fault or his suggestion that reset your settings.

For anyone with this issue, follow @nicodemus4802 's solution for now until the official fix.

1. Launch your GW2 original launcher (let it update if it has a new build) then look at the build number on the bottom right of the login window.

2. Open LB (close any updates/launchers it tries to open on start up), and manually repair each of your account. This is bugged at the moment as it won't close the launchers it opens, but you can close them after the repair patch.

3. Once done, close LB, and go to "%APPDATA%\Gw2 Launchbuddy" and open "Accs.xml" on Notepad. Search for "<gw2build>" and enter the newest build number you see on your original GW2 launcher in between "<gw2build>" and "</gw2build>".

You have to repeat if there is a new build.

**Comment by Jiansarys** [comment] 2021-05-27 11:20
@VathnaJr then how would relaunching it over and over suddenly kill my settings?  Anyway I'm done with this launcher. Every time there's an update I have to to go through a song and dance to get it working, and I'm just tired of it. This is the last I want to deal with it. Thanks for the info though. Have a wonderful day or night where you are.

**Comment by nicodemus4802** [comment] 2021-05-27 14:34
@Jiansarys I'm sorry to hear about your frustrations. I know that `Accs.xml` file handles all the settings for your various accounts. This file gets "edited" when you **_launch_** LB and when you **_close_** LB. I use a program called `Notepad++` which notifies you if the file somehow updates while you have it open to edit.

Plenty of players use older versions of LB, so there isn't anything wrong with reverting back to a previous version. I think @nrone is right that people shouldn't edit these files unless they are willing to risk loss of their files in the search to understand more about the program.

As a best practice for me, I also have a shortcut to the original game and use the [-image command line argument](https://wiki.guildwars2.com/wiki/Command_line_arguments) to download any GW2 client updates when [GW2Bot](https://gw2bot.info/) alerts me to new updates on Discord. This shortcut downloads GW2 client updates before I even run the LB program. I like this process because it's fairly foolproof, but I understand if it's a little more troublesome for others.

I think I will eventually create a batch file which runs the command line argument to download the newest update before opening LB, then launch the [GW2 add-on manager](https://github.com/fmmmlee/GW2-Addon-Manager/releases), and then launch LB. I have a whole unusual process where I also move my d3d9.dll to a separate folder so LB will only inject add-ons for my main account.

PS - @VathanaJr, thank you for outlining the process in a much more linear fashion. I think that will help others as they run into these issues.

**Comment by Lego6245** [comment] 2021-05-27 20:52
I think the issue might be in the API? From what I can tell, Launchbuddy queries the GW2API to grab the current build info:

https://api.guildwars2.com/v2/build

You can see it's still reporting the version as 115267, which is the last version that updated correctly. I think whomever pushed the new builds at ANet forgot to update the API as well.

**Comment by nicodemus4802** [comment] 2021-05-27 21:01
> I think the issue might be in the API? From what I can tell, Launchbuddy queries the GW2API to grab the current build info:
> 
> https://api.guildwars2.com/v2/build
> 
> You can see it's still reporting the version as 115267, which is the last version that updated correctly. I think whomever pushed the new builds at ANet forgot to update the API as well.

Good catch! I've posted something to their [forums](https://en-forum.guildwars2.com/topic/96243-gw2-client-build-number-stuck-at-115267/).

**Comment by WolfSabian** [comment] 2021-05-27 21:19
I had noticed the build number kept being saved as 115267 but wasn't sure why this was, if it was a problem originating within launch buddy or from information pulled from the Anet servers.

It's good to know where the issue is originating. Hopefully this gets fixed soon.

**Comment by ScrambledBrain** [comment] 2021-05-28 09:31
Another question is, what was fixed in LB v2.3.1, which points to exactly this API issue?

> - Fixed game updates which happened when the Gw2 API client version was not upto date yet.

**Comment by TheCheatsrichter** [comment] 2021-05-28 10:51
https://github.com/TheCheatsrichter/Gw2_Launchbuddy/releases/tag/2.3.3

**Comment by ScrambledBrain** [comment] 2021-05-28 11:12
Oh nice, TheCheatsrichter was working on it as I wrote here.
Tested v2.3.3 and it looks good: LB doesn't stuck anymore at updating the files and login with multiple accounts works too =)

**Comment by TheCheatsrichter** [comment] 2021-05-28 11:48
Thanks for the feedback! Pls keep the crash reports and feedbacks comming.  Some of these bugs seem to be very hardware specific and not reproduceable on my machine, so your reports are key!

**Comment by Flapjakk** [comment] 2021-05-29 00:08
Updated Launchbuddy, getting this when I select and account and hit launch:

![gw2 buddy problems](https://user-images.githubusercontent.com/84879230/120051876-85a26200-bff0-11eb-9faa-a3f67b0932b3.png)

**Comment by bloggingninja** [comment] 2021-05-29 05:54
Tested on v2.3.4 and is now working as expected for me. Great Job on the fix!

**Comment by aganod** [comment] 2021-06-01 10:53
> I was able to fix this by replacing `<gw2build>115267</gw2build>` with `<gw2build>115781</gw2build>`in the `%APPDATA%\Gw2 Launchbuddy\Accs.xml` file. I no longer get the "UPDATE REQUIRED" notice, and the login file no longer tries to update as I open LB. This will have to be my temporary fix until updates are properly applied to the `%APPDATA%\Gw2 Launchbuddy\Accs.xml` file.

This is still the only fix for me for the latest version 2.3.5

**Comment by TheLocalOutlierFactor** [comment] 2022-07-26 20:16
v3.0.4, auto-updates for login files don't work for me, saw this thread and decided to not start a new one.

whenever a new patch comes out, I start the game manually, wait for it to update, close the launcher and start LaunchBuddy. What it does is that it starts the game launcher and then just does nothing. Manually clicking login button does nothing, closing the launcher after that leaves the login file without an update. The only workaround is to recreate login files manually after each update.

I have a desktop PC with Windows 10, and a laptop with Windows 11. The issue is only present on the desktop PC with W10, but NOT on the laptop. I tried resetting the config file for launchbuddy, it didn't help. Also I can certainly remember that I didn't have that issue before, but I can't remember exactly when was the last time everything worked fine, because I primarily use launchbuddy on my laptop these days and not on my PC. Still, sometimes I need to use it on my desktop, so I'd like to find a fix.

**Comment by VathanaJr** [comment] 2022-07-26 20:26
> v3.0.4, auto-updates for login files don't work for me, saw this thread and decided to not start a new one.
> 
> whenever a new patch comes out, I start the game manually, wait for it to update, close the launcher and start LaunchBuddy. What it does is that it starts the game launcher and then just does nothing. Manually clicking login button does nothing, closing the launcher after that leaves the login file without an update. The only workaround is to recreate login files manually after each update.
> 
> I have a desktop PC with Windows 10, and a laptop with Windows 11. The issue is only present on the desktop PC with W10, but NOT on the laptop. I tried resetting the config file for launchbuddy, it didn't help. Also I can certainly remember that I didn't have that issue before, but I can't remember exactly when was the last time everything worked fine, because I primarily use launchbuddy on my laptop these days and not on my PC. Still, sometimes I need to use it on my desktop, so I'd like to find a fix.

What you're doing is correct when you open the launcher manually and wait for it to update first before you open Launch Buddy. However, it seems like you need to enable the option in LB to force update login data on LB open in the LB settings. I'm not sure of the exact wordings, but it should be there.

**Comment by Ashanielle** [comment] 2022-07-26 21:45
I have that option enabled and since the last update have been having the
issue where I have to hit Play on each launcher window and then Play again
in each account's character screens but I am able to get the logins to
successfully update so I haven't had to recreate them. It's just the extra
work of having to hit play twice now on each account. [image: image.png]

**Closed** 2023-02-19 02:05 UTC
Labels: status:testing, no-issue-activity
