### ISSUE TITLE
AutoUpdate to Loginfiles after 3/14/2023 Patch Hangs Indefinitely

### ISSUE THREAD

**Issue by Phdntom** [TheCheatsrichter/Gw2_Launchbuddy#424] opened 2023-03-14 16:26 UTC
**Describe the bug**
The autoupdate after the patch is permanently stuck with the message "Launchbuddy is updating Loginfile. This window should automatically close when the update is finished."

**To Reproduce**
As of now, it occurs every time I try to play the game with Launchbuddy rendering the launcher unusable.

**Expected behavior**
Per previous versions, launching should update each loginfile and then land on the main screen allowing account launch.

**First happend in LB Version**
3.2.4 on windows 11

**Screenshots**

**Comment by Phdntom** [comment] 2023-03-14 16:28
![Screenshot 2023-03-14 092809](https://user-images.githubusercontent.com/4334619/225072723-87b392fc-0631-479c-81b4-7de4a5d88748.png)

**Comment by Phdntom** [comment] 2023-03-14 16:29
![Screenshot 2023-03-14 092809](https://user-images.githubusercontent.com/4334619/225072986-bd069067-4db2-44e0-8678-e728070cc708.png)

**Comment by ATommasi** [comment] 2023-03-14 16:31
Can confirm, happens to me as well

**Comment by PressedRat** [comment] 2023-03-14 16:35
I am having the same problem.

**Comment by Wolfy339** [comment] 2023-03-14 16:43
Same, and to add:
- Even if you log in manually, the small window stays around.
- If you cancel the update while inside the game, you get n error message about he log-in file.
- Sometimes after canceling/closing the game window, it attempts a second relaunch of the same account.

**Comment by rafo121** [comment] 2023-03-14 16:51
Same problem for me.

**Comment by morpheus305** [comment] 2023-03-14 17:21
Having the same problem. Sucks that it happened on a mystic forge day as well.

**Comment by ProfYakkington** [comment] 2023-03-14 17:26
same here

**Comment by Stis** [comment] 2023-03-14 17:41
I bet "Coherent UI has been replaced with Chromium Embedded Framework to power web-based interfaces like the launcher and Trading Post." broke a lot of things...

**Comment by motorhead018** [comment] 2023-03-14 18:39
Can confirm as well. Also, the ability to create a new loginfile is broken as well.

**Comment by tentpeg** [comment] 2023-03-14 18:41
ditto same results

**Comment by Phdntom** [comment] 2023-03-14 19:08
> I bet
> 
> > Coherent UI has been replaced with Chromium Embedded Framework to power web-based interfaces like the launcher and Trading Post.
> 
> broke a lot of things...

I am not sure it's entirely related to this. I was able to run an older version of Launchbuddy 2.4.1 and everything works as expected without even needing to recreate or modify the Loginfiles from the 3.2.4 version.

**Comment by WolfSabian** [comment] 2023-03-14 20:35
After latest patch Launch buddy working properly now.

**Comment by motorhead018** [comment] 2023-03-14 20:40
> After latest patch Launch buddy working properly now.

This will only be temporary unfortunately. The Great GW2LB Creator will have to fix something in their code.

**Comment by Flapjakk** [comment] 2023-03-14 20:46
> After latest patch Launch buddy working properly now.

What do you mean latest patch?

My LB window still shows 3.2.4, but the problem suddenly stopped.

**Comment by ProfYakkington** [comment] 2023-03-14 20:47
> > After latest patch Launch buddy working properly now.
> 
> What do you mean latest patch?
> 
> My LB window still shows 3.2.4, but the problem suddenly stopped.

New gw2 patch: " Chromium Embedded Framework has been temporarily removed and reverted to Coherent UI while we investigate a crash."

**Comment by morpheus305** [comment] 2023-03-14 21:36
Good thing they removed it cause now I can get daily mystic forger on the rest of my alts before reset

**Comment by Flapjakk** [comment] 2023-03-14 23:37
> > > After latest patch Launch buddy working properly now.
> > 
> > 
> > What do you mean latest patch?
> > My LB window still shows 3.2.4, but the problem suddenly stopped.
> 
> New gw2 patch: " Chromium Embedded Framework has been temporarily removed and reverted to Coherent UI while we investigate a crash." - https://en-forum.guildwars2.com/topic/128855-game-update-notes-march-14-2023/#comment-1869692

Ah, thanks.

**Comment by Pekols** [comment] 2023-04-18 16:35
AutoUpdate to Loginfiles after 4/18/2023 Patch Hangs Indefinitely again

**Comment by WolfSabian** [comment] 2023-04-18 16:39
Chromium is back, and with it this issues has returned.

**Comment by Albacksen** [comment] 2023-04-18 17:01
Yep. It's ferkacte now. Guess we have to wait for a patch for Launchbuddy.

**Comment by S7Ado** [comment] 2023-04-18 17:05
u can also use https://github.com/TheCheatsrichter/Gw2_Launchbuddy/releases/tag/2.4.1 , it work's fine

**Comment by Wolfy339** [comment] 2023-04-18 17:08
Just came to check/confirm that the issue is back!

**Comment by serenity44** [comment] 2023-04-18 17:17
Confirming here as well. I opened GW2 on it's own and it updated just fine. Then opened launch buddy and hang. Even killing all of the attempts to update and just trying to make a new account or erasing an existing account and trying to remake results in me being able to login but LB does not recognize the game is running.

**Comment by TheWhiteWolves** [comment] 2023-04-18 17:30
https://github.com/TheCheatsrichter/Gw2_Launchbuddy/blob/master/Gw2%20Launchbuddy/Modifiers/LocalDatManager.cs#L160

@TheCheatsrichter From a quick scan of what LB is doing, seems we are stuck in the loop here waiting for the prelogin state. hope that helps with tracking down the issue with whatever Anet changed. assume they modified whatever it is you use to work out the state of the UI

**Comment by WolfSabian** [comment] 2023-04-19 00:36
> u can also use https://github.com/TheCheatsrichter/Gw2_Launchbuddy/releases/tag/2.4.1 , it work's fine

Oh man, as a current and hopeful means to get my accts online and multibox I'm attempting this.  I'm currently reliving the pain of "Client XXXX got closed or crashed before a clean start" with every account

**Comment by Flapjakk** [comment] 2023-04-19 01:34
> u can also use https://github.com/TheCheatsrichter/Gw2_Launchbuddy/releases/tag/2.4.1 , it work's fine

This triggers the "login file for *account name* did not update correctly" error cascade. And I never remember whether continue yes or continue no is the option that breaks it less.

**Comment by rav550** [comment] 2023-04-19 02:52
Which option breaks it less? I can't get 2.4.1 to work for me.

**Comment by Flapjakk** [comment] 2023-04-19 02:55
I think "yes."

After yes-ing everything, I closed it entirely and relaunched. Had to go through the rigamarole of downloading everything again, but this time no error messages and only 1 broken account.

**Comment by rav550** [comment] 2023-04-19 03:14
Thanks, seems to be working. I had to manually click close on the launcher window because it would just wait indefinitely, then select the 'yes' option in the launchbuddy dialog popup.

**Comment by TakuGW2** [comment] 2023-04-19 05:21
Sadly is 2.4.1 not working for me either, idk why but the launcher just closes and no loginfile is created

**Closed** 2023-11-13 01:36 UTC
Labels: no-issue-activity
