### ISSUE TITLE
Reshade support

### ISSUE THREAD

**Issue by TicWE** [TheCheatsrichter/Gw2_Launchbuddy#42] opened 2017-08-02 23:09 UTC
Does this support Reshade or do I need to run the game as usual to be able to use Reshade ?

**Comment by KairuByte** [comment] 2017-08-04 18:55
I'll be completely honest, I haven't tried it myself.

Your best bet would be to give it a shot, and see what happens. Though I would much appreciate it if you can let us know how it goes. I am trying to take a look into third party app support and I'm actually running into the problem of too little info on what people want/use, and what the problems are with those individual tools. Without knowing that "I use x tool and it only works if I don't use it with y tool unless I don't use LB", I'll just be shooting in the dark.

**Comment by TicWE** [comment] 2017-08-04 19:18
I usually use bgdm+Reshade but they don't work when I launch the game from LB

**Comment by KairuByte** [comment] 2017-08-04 19:45
Correct me if I am wrong but both of these are using the dll method, where you place a DLL in the bin folder?

**Comment by TicWE** [comment] 2017-08-04 20:00
Yes they are, I put them in the bin64 folder

**Comment by KairuByte** [comment] 2017-08-04 21:14
Where do you have LB running from? Is it in the game directory, a bin folder, or outside the GW environment completely?

If it is within any guild wars related folders, can you try placing it on your desktop or similar? I'm wondering if LB is getting hooked instead of GW and causing the problem.

I'm just starting to scratch the surface of the third party tool problems that are being experienced by most users, and I have very little info to work off.

**Comment by TicWE** [comment] 2017-08-04 22:04
It is in my Gw2 folder, I'll try to put it in my desktop

**Comment by TicWE** [comment] 2017-08-04 23:47
Even on the desktop, both don't work

**Comment by KairuByte** [comment] 2017-08-04 23:48
Ok, I'll give this a shot tonight. No promises though, I barely understand how dll injection works.

**Comment by KairuByte** [comment] 2017-08-05 08:12
So the problem is not LaunchBuddy, it appears to be an odd happening with the client and the way it handles -nopatchui which is needed to auto login. Unfortunately, because of this limitation, it appears that it is currently impossible to auto login and have ReShade work at the same time. LB and RS are not mutually exclusive though.

**Comment by Flyperd** [comment] 2017-08-06 11:06
Hi, I have been working on a addition to LaunchBuddy for loading dll's right from the add on menu. I have it working with the ui version of the injector I am in the process of merging the code and it should work seamless.

**Comment by KairuByte** [comment] 2017-08-06 15:28
Nice! I spent that last 48 awake trying to get that working, but just couldn't manage it. Dll injection is not my forte. I'll definitely be digging through your pull request to sop what I was messing up on. 🤣

Yay for more contributors!

**Comment by Flyperd** [comment] 2017-08-06 20:08
Well still having a lot of problems and i modified a lot of other things as well so probably will not pull request. Also BGDM doesn't want too work properly

**Comment by hasosoft** [comment] 2017-08-06 20:26
What I've noticed from using arcdps and bgdm is that you put the d3d9.dll in the main folder if you want to start it from the command-line/shortcut/launchbuddy, and the rest of the DLLs in the bin64 folder.

Making the folder structure look like this: 

>G:\Games\Guild Wars 2\.
|   d3d9.dll
|   Gw2-64.exe
|   Gw2.dat
|   
\\---bin64
>   + |   bgdm.dll
    |   CoherentUI64.dll
    |   CoherentUI_Host.exe
    |   d3d9.dll
    |   d3d9_chainload.dll
    |   d3dcompiler_43.dll
    |   ffmpegsumo.dll
    |   icudt.dll
    |   libEGL.dll
    |   libGLESv2.dll
    |   tmp.dll
    |   
   \ \---locales

**Comment by Flyperd** [comment] 2017-08-06 20:27
Yeah i know but I dont want too load them but inject them.

**Comment by hasosoft** [comment] 2017-08-06 20:34
I think the whole idea of using a proxy d3d9.dll was based around the fact that the gw2 (or AVs for that matter) probably won't allow injection of dlls anyway. Wouldn't it just be easier as a workaround to create/hide/unhide the dll files on load so the gw2 launcher catches on to them in the regular way.

I applaud your efforts but it seems like a lot of work for something that might potentially create a lot of issues even if it works. It might even be easier to produce your own d3d9 proxy dll to handle the dynamic loading of dpsmeters or reshade.

**Comment by Flyperd** [comment] 2017-08-06 20:41
Yeah that is what it does, maybe the word injector is not really correct. it catches the d3d9 request and loads dpsmeters and reshade. It works for arc but bgdm doesn't  want too load unless its in the bin directory.

**Comment by hasosoft** [comment] 2017-08-06 20:50
That's because the bgdm d3d9.dll specifically looks for the dll files "bin64\\tmp.dll" and "bin64\\bgdm.dll" in the DllEntryPoint function.

If it doesn't find them there you get the message  "Failed to load the meter."

**Comment by KairuByte** [comment] 2017-08-06 21:07
Ah ok. This is close to what I settled on last night. 

I was originally intending on injecting in real time, which I managed to do with custom code. But I can't get the hooks used in reshade to properly load if I push in while love, something about the way it works seems to require it to be loaded on startup before directx has been accessed. 

The bdgm method should be easily worked around though, the loader is what does that checking, it is intended for live updating of the hook.

I have three methods in mind but they all have drawbacks. 

One is the current method which would require a chain loader dll, and could still cause problems when loading two libraries that touch the same areas.

The second is to hook directly into directx at the system level using LB, which would allow fine tune loading of whatever we need. This would be easier to handle on the code side but still could cause problems with incomparable code. 

Third seems to best but also the least likely to happen. Convince the authors of the tools to alter the code in a way that allows run time injection instead of the current pre launch method. I like this the best as it would allow dynamic loading and unloading of the libraries as needed. 

I'm working on the first for now.

**Comment by KairuByte** [comment] 2017-08-16 05:57
I'm personally backing out on this feature in particular for the time being. The recent banning of the BGDM dev has made me wary about working on something that pulls external DLL's into the client, as I don't want myself or others on my network banned. Others are free to take up the mantle of course, but any code/info/etc is not being pushed into a branch or merged by myself for the time being.

**Comment by KairuByte** [comment] 2018-12-12 19:34
The latest version should be able to handle this now, give it a shot and let us know if it works!

**Closed** 2018-12-12 19:36 UTC
Labels: status:complete, type:feature
