### ISSUE TITLE
Launchbuddy issues with McaFee & Webroot

### ISSUE THREAD

**Issue by DougSands** [TheCheatsrichter/Gw2_Launchbuddy#62] opened 2018-03-19 14:55 UTC
Hi -- Tried to download 1.5.1 and both of these apps, Webroot and Mcafee, flag GW2_Launchbuddy as a bad actor. I went to this site and while there is a link for 1.5.2, nothing downloads from it. I thought you folks should know.
https://github.com/TheCheatsrichter/Gw2_Launchbuddy/releases/tag/1.5.2

**Comment by TimothyVandenbrande** [comment] 2018-03-19 15:28
Duplicate of https://github.com/TheCheatsrichter/Gw2_Launchbuddy/issues/56

**Comment by KairuByte** [comment] 2018-04-09 16:52
Closing as dupe of #56 (As noted by @TimothyVandenbrande)

**Closed by KairuByte** 2018-04-09 16:52 UTC
Labels: status:duplicate
