### ISSUE TITLE
setting up Reshader

### ISSUE THREAD

**Issue by leogono** [TheCheatsrichter/Gw2_Launchbuddy#58] opened 2018-01-30 02:17 UTC
Does anybody know any guide on how to setup reshader with Launchbuddy? I can see the option but don't know which files to download.

**Comment by KairuByte** [comment] 2018-02-01 06:45
Latest reshade versions are broken with LaunchBuddy. There is something that causes reshade to crash and unload immediately after it's initial load. See also #42.

**Comment by KairuByte** [comment] 2018-02-01 06:46
Duplicate of #42

**Closed** 2018-02-01 06:48 UTC
Labels: status:duplicate

**Comment by leogono** [comment] 2018-02-01 07:05
Thanks. I did not know you can add the .dll on the root folder. 👍 it's working now.
