### ISSUE TITLE
1.5.3 attempt to deserialize an empty stream

### ISSUE THREAD

**Issue by Embersz** [TheCheatsrichter/Gw2_Launchbuddy#71] opened 2018-07-06 03:30 UTC
So I click the shortcut on my startup bar and [this error message shows up ](https://i.imgur.com/ZN8CR6E.png) shortly after the GW2LB loads up without any of my auto login account credentials. 

It's been behaving perfectly normally up to this point and I've been using this app for a long time and never seen this issue before.

Any chance I can fix this without resetting all the passwords?

**Comment by KairuByte** [comment] 2018-12-16 09:11
So, way late to the party, sorry. Unless closing the app and reopening fixed it, the chances are slim there is any way to recover, unfortunately.
Latest version should have this happen less often (it was already extremely rare) because the settings file is written to much less often.
I'm going to close this issue as unreproducable, but if you run into it again, please let us know with all details you can think of the most recent working run.

**Closed by KairuByte** 2018-12-16 09:11 UTC
Labels: type:cant_reproduce
