### ISSUE TITLE
Intermittent failure to fill in account email on login screen

### ISSUE THREAD

**Issue by JinxLuckless** [TheCheatsrichter/Gw2_Launchbuddy#353] opened 2022-07-21 02:48 UTC
After yesterday's GW2 patch, LaunchBuddy no longer seemed to keep my login information. I would launch account 1, and the username would be blank. Same for the other 2 accounts. I tried resetting the login info via Account Settings/Set Loginfile, but had no luck. Even when the username field is empty, if I reenter the username manually and click login, it seemingly always logs me in without my having to type the password.

I made fresh account profiles (without cloning old ones), but had the same issue. I also deleted LaunchBuddy & all appdata files, but when I reinstalled LaunchBuddy, I had the same issue. I also reinstalled Guild Wars 2 today, but still had the issue. At this point, it seems random-- sometimes when I try to launch an account, the username shows up just fine. Other times, the username will be blank. I haven't been able to determine any kind of pattern to this.

In fact, I logged into the same account 3 times in a row (without logging into either of the others in between) to test it, and the first & second time it worked fine, and the third time, the username was blank without my changing any settings. I logged into a different account 3 times in a row, and it worked fine all 3 times. When I tried a 4th time, the username was blank.

I'm not sure what to try at this point-- like I said, I've manually removed all LaunchBuddy settings and downloaded a fresh copy, I've created fresh account profiles, and I've uninstalled & reinstalled Guild Wars 2.

**Comment by Behealilu** [comment] 2022-07-21 16:02
Same Issue here with all accounts. Seems to appear randomly. If I try to start one account it might have the e-mail-adress missing. If I recreate the loginfile, it might work for the next login, but not all the time. For example just now I reacreated one and it didn't work. So I recreated it a few more times (tried to login after each recreation) and it worked on the third or fourth time. Sometimes on the first try.
Needless to say it's a little pain to login into more then 10 accounts :D

**Comment by TheLocalOutlierFactor** [comment] 2022-07-21 19:48
same issue here, after today's hotfix for the the last patch it got even worse and now consistently doesn't fill in email. Repairing doesn't work, setting up a new login file doesn't work either.

**Comment by Siofral** [comment] 2022-07-22 22:01
Same issue here. It doesn't seem to matter how I fill in the information. The backup information isn't reliably saved and it certainly isn't used. I get the wrong login information more often than the correct one. This whole portion of the app is not working correctly.

**Comment by JinxLuckless** [comment] 2022-07-22 23:55
I'm on Windows 10. The one semi-workaround I've found is to just enter in the email address manually for each account if it isn't entered, and then the password is always already set correctly. So at least I only have to have half the info ready?

**Comment by TheLocalOutlierFactor** [comment] 2022-07-26 20:03
what apparently solved my issue is, stupidly enough, turning off windows scaling. I have a pretty small laptop screen with FullHD resolution, so I was using 150% scale in windows display settings. I decided to try to turn it off (make it 100%) and so far so good, no empty email field.

**Comment by JinxLuckless** [comment] 2022-08-03 00:59
I have a pretty normal-ish sized desktop screen (not huge, but... only a little small I think) but even so, if I turn windows scaling off, the words become too small to read. But for now, I still can at least manually enter in the email address when it doesn't enter it automatically. I only have 3 accounts, so I can handle that.

**Comment by akeck** [comment] 2022-08-03 11:20
> I only have 3 accounts, so I can handle that.
I have 30 accounts (don't ask...), and I can't handle it :)
My monitor is 4k, and without scaling, it's nearly impossible to read anything.
Try to open Visual Studio on 4k... kinda funny :)

**Comment by Behealilu** [comment] 2022-08-04 06:32
> > I only have 3 accounts, so I can handle that.
> 
> I have 30 accounts (don't ask...), and I can't handle it :) My monitor is 4k, and without scaling, it's nearly impossible to read anything. Try to open Visual Studio on 4k... kinda funny :)

same for me. i got about 27 Accounts and my monitors are 4k - and it's a real pain cuz sometimes (like right now) i have to enter every single mail manually. And you have to enter it during the DDoS protection timer cuz otherwise the hole timer-thing is messed up. (And yes. today it's every single mailadress!)

**Comment by lamvuong2019** [comment] 2022-08-08 06:54
> what apparently solved my issue is, stupidly enough, turning off windows scaling. I have a pretty small laptop screen with FullHD resolution, so I was using 150% scale in windows display settings. I decided to try to turn it off (make it 100%) and so far so good, no empty email field.

I can confirm that after doing this it works.

**Comment by TheCheatsrichter** [comment] 2022-08-18 17:13
please test version 3.0.5 and report if the error has been solved.

**Comment by akeck** [comment] 2022-08-18 19:32
nope... tried two accounts and the first one didn't work again. Email field was empty.
In the previous version, it worked here with 100% zoom, with 125% same problem in 2.x and 3.0.5

**Comment by TheCheatsrichter** [comment] 2022-08-18 19:35
I am gonna run this on a different machine tomorrow. Hopefully I can reproduce the issue there

**Comment by akeck** [comment] 2022-08-18 19:39
(crossing fingers...)
However:
Thank you for dark mode!
Thank you for Select All!
Thank you for Daily Select!
Thank you for not loosing selection when mouse pointer leaves the window!

Thank you for still trying to fix it for us :)

**Comment by Behealilu** [comment] 2022-08-19 04:11
> please test version 3.0.5 and report if the error has been solved.

Doesn’t work for me :( same Issue on nearly the same number of accounts. If there is anything to help you with to find the Problem, pls tell me :) it‘s 100% reproducible so if I can help you anyhow it might be easier for you than testing on another machine ☺️

**Comment by Behealilu** [comment] 2022-09-01 16:20
Just FYI: Update 3.0.6 haven't changed anything according to this this issue.

**Comment by nolifeSnorlax** [comment] 2022-09-07 10:11
Just ran into this issue. The lauchbuddy would open my gw2 launcher but didn't type in login information.
I had my Windows scaling set to 125%.

After reducing the scaling to 100% the issue is fixed - I'd love a patch though since I can't deal with everything this small :(

**Comment by ubereffect** [comment] 2022-09-07 19:54
You should be able to adjust Windows DPI Scaling for individual programs like Launchbuddy and/or Guild Wars 2, while keeping it set to 125% or higher for everything else. I'd suggest right-clicking your Launchbuddy and/or GW2 program/exe file(s), then select Properties/Compatibility/Settings/'Change high DPI settings', and playing around with the settings there.

While I can't say I understand what these settings do, precisely. It should be easy enough to get working through trial and error. If you manage to get it working, but find everything in game is too small, try lowering your in game resolution.

For what it's worth, I found that Launchbuddy is System DPI-Aware, Guild Wars 2 is Per-Monitor DPI-Aware, and CoherentUI_Host.exe (Trading Post / Gem Store) is DPI-Unaware.

**Comment by TheLocalOutlierFactor** [comment] 2022-10-10 12:22
it appears that the issue is with the game's client itself, not launchbuddy. My e-mail field would sometimes be empty upon starting the launcher outside of launchbuddy.

**Comment by goncalo532** [comment] 2022-11-29 16:29
Still an ongoing problem on 3.1.0.

**Comment by TheCheatsrichter** [comment] 2022-12-04 19:47
https://github.com/TheCheatsrichter/Gw2_Launchbuddy/issues/383

**Comment by arbitergrim** [comment] 2023-02-22 04:17
still experiencing this issue of LB not auto-filling the email address even with GW2LB 3.2.4. as [TheLocalOutlierFactor] has pointed out, it appears to only affect w11 machines. it only happens occasionally on my w10 desktop. happens more often on my w11 laptop. hopefully this is resolved in 4.0

**Closed** 2023-09-19 01:32 UTC
Labels: type:possible bug, status:testing, no-issue-activity
