### ISSUE TITLE
3rd Party Support request

### ISSUE THREAD

**Issue by ihavenodamage** [TheCheatsrichter/Gw2_Launchbuddy#221] opened 2021-04-10 12:37 UTC
1*  u have discord for support, or only github?
2*  Is it possible to open several gw2 with all addons working? example arcdps, d912, reshade, radial
3*because the first game that opens with all add-ons, and the other games do not work with any add-on

**Comment by TheNasbit** [comment] 2021-05-08 09:17
@ihavenodamage 
1. Just github
2. It is possible. At least when no Instance is running all addons will start for all selected accounts. If there already running instances, the dlls are not loaded for some reason. So it could indeed be a launchbuddy issue. @TheCheatsrichter

**Comment by TheNasbit** [comment] 2021-05-08 09:43
Duplicate of #194

**Closed** 2022-12-22 01:53 UTC
Labels: type:not launchbuddy, no-issue-activity
