### ISSUE TITLE
How do you make launch buddy stop opening web pages?

### ISSUE THREAD

**Issue by Flapjakk** [TheCheatsrichter/Gw2_Launchbuddy#421] opened 2023-01-23 02:08 UTC
When I launch GW2 using launch buddy, about 60% of the time it opens the latest news item in my web browser. Right now it's [https://www.guildwars2.com/en/news/gem-store-update-imperial-crane-raptor-skin-and-lunar-rabbit-helm-and-stompers-package/.](https://www.guildwars2.com/en/news/gem-store-update-imperial-crane-raptor-skin-and-lunar-rabbit-helm-and-stompers-package/)

Of 10 account logins, it's always at least 4, frequently 6, and occasionally all 10. Today it was 14 times out of 10 accounts (launch buddy kept crashing so had to relaunch several accounts)

It's just hit or miss. No apparent reason for when it triggers and when it doesn't. But it's more often than not. 

Some discussion on the official forums: https://en-forum.guildwars2.com/topic/126351-launching-gw2-opens-a-webpage/

**Comment by ManiakNL** [comment] 2023-01-26 11:34
Duplicate of: https://github.com/TheCheatsrichter/Gw2_Launchbuddy/issues/394

**Closed** 2023-08-22 01:29 UTC
Labels: no-issue-activity
