### ISSUE TITLE
GW2 won't launch via LB after today's patch (2019-03-05)

### ISSUE THREAD

**Issue by kazerniel** [TheCheatsrichter/Gw2_Launchbuddy#124] opened 2019-03-05 21:37 UTC
I updated my GW2 client, but LB still tries to download something via the GW2 launcher when I try to launch a profile. (It also says something like "LaunchBuddy is trying to update..." but the window disappears too fast to read it.) Then the GW2 launcher gives the following error:

> Download failed! Please check your internet connection and try again. (5)

Even though my internet connection is working fine, and if I launch the GW2 client outside of LB it runs all right, and needs no further updates.

**Comment by codingqt** [comment] 2019-03-06 01:21
Seems it broke something in the login file. If you re-do the "Set Loginfile" (not repair), it should be fixed. Worked for me, anyway.

**Comment by jacob-keller** [comment] 2019-03-06 05:38
I had the same problem, I had to manually re-create login files, bit annoying since it caused me to lose some settings.

**Comment by nicodemus4802** [comment] 2019-03-06 17:04
I was able to go into <%APPDATA%\Gw2 Launchbuddy\Accs.xml> and change the build number back to what it was (95535) instead of what it was trying to change the build number to (95555).

**Comment by kazerniel** [comment] 2019-03-06 18:44
Setting the loginfiles again worked for me too :)

**Comment by Noxicon7** [comment] 2019-03-06 19:34
I remade my login files, but now the game launches in Full Screen instead of Windowed Full Screen even though its configured for such in the Graphics Configuration section.  LB hates me I think.

**Comment by SaiyanOfDarkness** [comment] 2019-03-07 00:35
The reason this is failing is because LaunchBuddy forces -shareArchive  .. instead of using -image to update.

**Comment by SaiyanOfDarkness** [comment] 2019-03-07 06:20
Also just for reference, this is the exact same problem as this.. https://github.com/TheCheatsrichter/Gw2_Launchbuddy/issues/115

**Comment by PalantirTinuviel** [comment] 2019-03-07 13:31
LB doesnt work for me at all now. Tried to repair file, then remade LoginFiles, but when starting more than one account, GW crashes.

**Comment by PalantirTinuviel** [comment] 2019-03-07 13:42
Found a way for me to get LB started again:
- deleted all Accounts in LB
- deleted Accs and Loginfiled in AppData
- started LB and created 1 Acc, and logged in this Acc via LB, chose a char and entered the game
- logged out Acc 1, closed the GW2-login-pop-up
- closed LB and restarted LB
- created second Acc (without using "clone"), started this Acc via LB and entered the game and so on for each Acc
-> got 5 Accs running without any crashes

**Comment by kazerniel** [comment] 2019-03-07 19:53
The subsequent patches since then seem to break the loginfile again.

**Comment by SaiyanOfDarkness** [comment] 2019-03-08 00:25
Every new patch, even minor you have to re-create new loginfiles, or patch them another way individually.  This needs to be addressed soon.  Quite frustrating.

**Comment by jacob-keller** [comment] 2019-03-08 16:22
I've been able to get the "repair login file" button to work, but only intermittently. I'm not sure what causes it to break, but it pops up a thing saying that some other process has the 1.dat open so it can't update it.

**Comment by nicodemus4802** [comment] 2019-03-08 16:55
I don’t get that error IF I use a shortcut before opening up LB which uses the -image argument. Once the .dat file for the game (about 40GB) has been updated, I can then open up LB to update the .dat file for each respective account for the login credentials.

**Comment by TheCheatsrichter** [comment] 2019-04-19 19:20
This error was very likely caused by an API downtime / delay. LB actually checks if your current Gw2 build is in synch with the buildnumber of the API. So if the API is either down or the API does not properly update the buildnumber on a new release, then your gw2 client will actually stay outdated without any "You must update" Popup. 

Can you guys confrim this?

**Comment by nicodemus4802** [comment] 2019-04-19 20:53
The above statement is true if the end user does not already have LB open and running prior to an update coming out. Additionally, I have experienced errors related to this when I open LB then try to launch multiple accounts at the same time without first updating their respective DAT login files. If I recall correctly, the error which pops up in that scenario says something along the lines that an instance of Guild Wars 2 is already in use and cannot download the new DAT update. This causes the Accs.xml to update with an incorrect build number which I have to manually change to fix the issue.

Lately when I notice there's an update, I will close and relaunch LB to update to the new GW2 build. Then, I'll go into the settings for each individual account and tell it to "Repair Loginfile". This usually keeps me from running into any issues.

**Comment by jacob-keller** [comment] 2019-04-20 00:43
I have similarly had to ensure that I do not launch multiple accounts,
instead repair manually each login file first. Otherwise the data can get
out of date and corrupt the login files and I have to regenerate them.

Regeneration is annoying as all the settings are lost. I have to open each
login file outside of launch buddy and edit the setting and exit.

**Comment by TheCheatsrichter** [comment] 2019-04-22 14:08
Hotfix 1.9.1 introduced some new bugfixes regarding this issue. Please test it and report back if it still happens. I will tag this bug as completed until it reoccurs.

**Comment by kazerniel** [comment] 2019-04-23 16:23
The repair or recreation options still don't work for me, I had to re-set the account logins manually after today's update, as in previous versions.

**Comment by TristisOris** [comment] 2021-10-06 06:41
same happens after last patch, can't run 2nd account.
but "repair" function fixed this.

**Comment by kazerniel** [comment] 2021-10-06 09:02
For me it was fixed by a later patch.

**Closed** 2022-12-31 01:51 UTC
Labels: type:bug, status:testing, no-issue-activity
