### ISSUE TITLE
1.8.9 has UAC shield and asks to allow changes made to system. Issues using GW2 Taco

### ISSUE THREAD

**Issue by HGLatinBoy** [TheCheatsrichter/Gw2_Launchbuddy#122] opened 2019-02-11 06:36 UTC
I'm not sure if the UAC shield part of the newest version of LB or if my PC is just adding it on. But its causing an issue with GW2 not being able to run because it does not have the same level of privileges as GW2. This only happens when I launch GW2 using LB. If I launch the client normally Taco works just fine. 

Running GW2 with Administrative privileges causes it to crash so that doesn't work.

**Comment by Throne3d** [comment] 2019-02-11 23:06
I think this is a duplicate of #112? I don't know why GW2TacO would crash if you ran it with administrative privileges, though – it doesn't for me.

**Comment by SaiyanOfDarkness** [comment] 2019-02-13 09:29
UAC is something that's always pissed me off.. Every time I reinstall windows.. I disable that shit right away..

**Comment by KairuByte** [comment] 2019-03-06 18:50
Duplicate of #112

**Closed by KairuByte** 2019-03-06 18:50 UTC
Labels: status:duplicate
