### ISSUE TITLE
Creating/Recreating Loginfile overwrites all accounts' loginfile

### ISSUE THREAD

**Issue by jdes375** [TheCheatsrichter/Gw2_Launchbuddy#243] opened 2021-06-01 21:27 UTC
I can recreate individual loginfiles for each of my accounts, but once I have done so it applies to each account. I can recreate for each account and it uses the correct info for each account but just overwrites the others.

**Comment by sn0opy** [comment] 2021-06-07 18:40
Probably a duplicate of #235 which has just been fixed.

**Comment by hansyulian** [comment] 2021-07-13 03:26
i got the same problem, gonna try to check #235

**Closed** 2022-12-18 01:52 UTC
Labels: no-issue-activity
