### ISSUE TITLE
TacO cannot find GW2MumbleLink

### ISSUE THREAD

**Issue by DrOpossum** [TheCheatsrichter/Gw2_Launchbuddy#202] opened 2020-12-02 16:59 UTC
Hey guys, 

I've been encountering some issues with TacO and LB recently. Not sure whether or not this is your part of the code or an issue related to TacO but since you're working on it together I'll just dump what I found here. 

So when I start a single client using Launchbuddy and afterward start TacO using the button in Launchbuddy, everything works fine. However, if I try to do the same with multiple clients running, it works sometimes. I'm currently still trying to find a way to reliably reproduce this problem and keep you update If I find it. 

TacO states the following problem in the log:
 `Closing TacO because GW2 with mumble link GW2MumbleLink2 was not found in under a minute`
The number (in this case **2**) changes according to the account I tried to start it on.

I'm currently using d912pxy as well as ReShade and did not encounter any other problems with this setup. Everything is updated to the most recent version, running with admin permissions and in windowed fullscreen. Versions can be found below:

| Software | Version |
|--------|-----------|
| d912pxy      | `2.3.0`| 
| ReShade      | `4.8.2`|
| LaunchBuddy      | `2.2.1`|
| TacO| `47.2802r`|
| Game| `109065`|

Looks like someone had a similar problem [here](https://www.reddit.com/r/GW2TacO/comments/inulxy/taco_worked_then_doesnt/g4hoxdg?utm_source=share&utm_medium=web2x&context=3). 

That's what I gathered so far. If you require any additional details regarding my setup or any logs, feel free to reach out. 

Best regards
Felix

Edit: Table was broke

**Comment by DrOpossum** [comment] 2020-12-02 19:19
After inspection using ProcessExplorer I found out that the `-mumble` parameter is not set. If I'm not wrong [this](https://github.com/TheCheatsrichter/Gw2_Launchbuddy/blob/master/Gw2%20Launchbuddy/ObjectManagers/ClientManager.cs#L434) line should be responsible for adding it. Any idea why this might not be working?

**Comment by DrOpossum** [comment] 2020-12-03 21:53
Reverting back to 2.2 resolves this. Seems to be a problem with the line mentioned above.

**Comment by ScrambledBrain** [comment] 2020-12-20 18:33
Hi,

https://github.com/TheCheatsrichter/Gw2_Launchbuddy/releases/tag/2.2.1 states:
- Only use custom mumblelink on multiboxed clients to further support software which does not support multiboxed mumble links

For this reason **_LB starts all first selected GW2 accounts without a mumble link_** !
Only if already at least one GW2 client is running and another GW2 account is started later in LB, they will get started with a mumble link.

The issue is now: **_TacO starts everytime with the mumble link_** for each GW2 account **_resulting in TacO times out_** trying to bind to non-existing GW2 mumble link.

I think, it would be an idea to put an option to de-/activate mumble links at all or separated for each account.

**Comment by TheCheatsrichter** [comment] 2021-02-12 16:06
This issue should be resolved with https://github.com/TheCheatsrichter/Gw2_Launchbuddy/commit/ed2914ae66a3957fe5921b4620dde1733f752d27
Tested it on my machine and seems to work. First acc now gets the correct Mumble Link.

**Comment by ScrambledBrain** [comment] 2021-02-14 07:43
> This issue should be resolved with [ed2914a](https://github.com/TheCheatsrichter/Gw2_Launchbuddy/commit/ed2914ae66a3957fe5921b4620dde1733f752d27)
> Tested it on my machine and seems to work. First acc now gets the correct Mumble Link.

Thanks TheCheatsrichter. At first I was confused, because no account started with a mumble link but then I found the option in "Account settings > {account} > Advanced Settings: Use Custom Mumble Link" and this worked like a charm now.

**Closed** 2021-03-19 17:48 UTC
