### ISSUE TITLE
Client crash upon selecting 'Add'

### ISSUE THREAD

**Issue by Zeus6900** [TheCheatsrichter/Gw2_Launchbuddy#219] opened 2021-04-07 05:25 UTC
Hello! So just recently installed the program to use. When trying to 'Add' any account(s) the client immediately crashes with a double pop-up client crash message, unsure how to fix or work around it. Would appreciate any tips how to address the problem!

https://user-images.githubusercontent.com/82077372/113814630-46f0e800-97b5-11eb-846a-a464b6320bbe.mp4

**Comment by TheCheatsrichter** [comment] 2021-04-28 17:36
Possibly a duplicate of https://github.com/TheCheatsrichter/Gw2_Launchbuddy/issues/223

**Closed** 2021-04-28 17:37 UTC
Labels: status:duplicate
