### ISSUE TITLE
Ignores the parameters sometimes.

### ISSUE THREAD

**Issue by Ecmelt** [TheCheatsrichter/Gw2_Launchbuddy#35] opened 2017-02-28 04:38 UTC
This happened to me with previous versions as well, sometimes it'll launch whatever is the latest version i launched regardless of what i choose.

Example: -32 -autologin still opens 64b client, or sometimes just -autologin opens 32b even if it is not ticked. 

If i tick or untick ANYTHING under "general" it just resets back to whatever is picked at the moment the moment i reopen the launcher.

Example: -32 is selected yet it opens 64b. I deselect -32 quit launchbuddy, open again and -32 is selected again. Yet it keeps launching 64b regardless of if i select it or not.

I don't know how to fix it except "set directory" again which seems to fix the first issue. However things still won't be remembered.

**Comment by TheCheatsrichter** [comment] 2017-03-03 18:13
This is a result of Guild Wars2 not beeing closed correctly. Launchbuddy itself actually does not save the used parameters. It imports them from the .xml file of the gw2.exe itself. So whenever your game crashes or  can't close correctly, thoes parameters won't be saved and therefore old once will be used.

**Comment by Ecmelt** [comment] 2017-03-03 18:15
That is weird, no crashes or anything happening for it to cause this. What counts as "not closed correctly" do you know? Pressing the X button after you press ESC instead of exit game maybe? Because that is how i close my gw2.

**Comment by TheCheatsrichter** [comment] 2017-03-03 18:17
In my ealier test this behavior only occured whenever I closed Gw2 via Taskmanager or Windows itself.

**Comment by KairuByte** [comment] 2017-08-04 19:03
I'll check in a bit but it would likely happen if we don't ask the client to close gracefully and instead just force close it. This will be the difference between Process.Kill() and Process.CloseMainWindow().

Short term this would fix the problem caused by the instance manager, but not normal crashes.

Long term I am planning on adding individual configuration profiles similar to the graphics settings profiles, and we may want to explore ignoring the flags the client stores completely except for first run.

**Comment by KairuByte** [comment] 2017-08-04 19:49
I have included graceful close with force on fail, this should be mitigated with the next release of LB. Crashes will still cause this problem however.

**Comment by KairuByte** [comment] 2018-12-12 19:35
Closing as fixed in 1.7

**Closed by KairuByte** 2018-12-12 19:35 UTC
Labels: type:enhancement, type:not launchbuddy
