### ISSUE TITLE
Everything super slow since 2 Aug patch

### ISSUE THREAD

**Issue by Drogon1234** [TheCheatsrichter/Gw2_Launchbuddy#357] opened 2022-08-04 06:18 UTC
Since last patch everything is super slow for me.

Updating login files takes much longer than before

Logging in multiple accounts is very slow, I have started manually clicking the log in button as it takes way too long otherwise

Going back to launchbuddy via alt tab to launch more accounts doesn't seem to work properly. Most of the time the alt tab just doesn't do anything and it keeps my open game on the forefront.

Anyone else experiencing this?

**Comment by Aussiemon** [comment] 2022-08-04 07:09
Same bug as #356.

WINNSI.DLL is used for autologin, updating local.dat, and creating new logins; and the module doesn't exist in the GW2 process anymore.

**Comment by TheCheatsrichter** [comment] 2022-08-17 15:47
Duplicate of https://github.com/TheCheatsrichter/Gw2_Launchbuddy/issues/356
Issue is beeing worked on

**Closed by TheCheatsrichter** 2022-08-17 15:47 UTC
